--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/HyperBackup
build-by-default: true
branches:
- main
projects:
  HyperBackup:
    path: ""
    lint:
      phpstan: false
...
